name: Request Page Build
on:
  schedule:
    - cron: '45 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            // Get day before
            const d = new Date();
            d.setDate(d.getDate()-2);

            // Commits since day before
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: d.toISOString()
            });

            // Filter only creation of markdown (no footer)
            const filtered = commits.data.filter(function(c){
              const msg = c.commit.message;
              return (msg.endsWith(".md") && msg.startsWith("Create") && !msg.includes("footer"));
            });

            // Loop filtered
            for (const commit of filtered){

              // Get creation commit and take filename
              const single = await github.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commit.sha
              });

              // Get updated file content
              const file = await github.repos.getContent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: single.data.files[0].filename
              });
              console.log(file.data.path);
              const content = Buffer.from(file.data.content, 'base64').toString('binary')
              console.log(content.includes('{% include footer.md %}');
              // console.log(window.atob(file.data.content));
              // decode content and add footer if not present
            }

            console.log(filtered.length)

            // Trigger Pages rebuild
            const build = await github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
