name: Request Page Build
on:
  schedule:
    - cron '0 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            const d = new Date();
            d.setDate(d.getDate()-1);
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const build = await github.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            console.log(commits);
