name: Request Page Build
on:
  schedule:
    #- cron: '12 * * * *'
    - cron: '1 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            // Get day before
            const d = new Date();
            d.setDate(d.getDate()-1);

            // Paginate commits since day before
            // Filter messages containing "Create *.md" except "footer"
            const commits = await github.paginate("GET /repos/{owner}/{repo}/commits",
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                since: d.toISOString()
              },
              (response) => response.data.filter((commit) => {
                  return (commit.commit.message.endsWith(".md") && commit.commit.message.startsWith("Create") && !commit.commit.message.includes("footer"))
                })
            ).then(async (filtered) => {
              
              // Loop filtered commits
              let added_footer = 0;
              for (const commit of filtered){

                // Get creation commit and take filename
                const single = await github.repos.getCommit({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: commit.sha
                });

                // Get updated file content
                const file = await github.repos.getContent({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  path: single.data.files[0].filename
                });
                
                // Decode content and check if footer is present
                const content = Buffer.from(file.data.content, 'base64').toString('binary');
                if (!content.includes('{% include footer.md %}')) {
                  
                  // Append footer
                  const new_content = content + '\n{% include footer.md %}';
                  const encoded_content = Buffer.from(new_content, 'binary').toString('base64');
                  const update = await github.repos.createOrUpdateFileContents({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    path: file.data.path,
                    message: 'Append footer to ' + file.data.name,
                    content: encoded_content,
                    sha: file.data.sha,
                    committer: {
                      name: 'trasparente',
                      email: 'stradatrasparente@gmail.com'
                    },
                    author: {
                      name: 'trasparente',
                      email: 'stradatrasparente@gmail.com'
                    }
                  });
                  console.log('Appended footer to ' + file.data.name);
                  added_footer++;
                }
              }

              if (added_footer.length > 0) {
                console.log('Updated ' + added_footer.length + ' files. Exit');
                return;
              }

              // Trigger Pages rebuild
              console.log('No file updated. Rebuild');
              const build = await github.repos.requestPagesBuild({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              return build.status;

            });
