name: Request Page Build
on:
  schedule:
    - cron: '25 * * * *'
    #- cron: '1 */24 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.ACTIONS }}
          script: |
            // Get day before
            const d = new Date();
            d.setDate(d.getDate()-2);

            // Commits since day before
            const commits = await github.paginate("GET /repos/{owner}/{repo}/commits",
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                since: d.toISOString()
              },
              (response) => response.data.filter((commit) => {
                  return (commit.commit.message.endsWith(".md") && commit.commit.message.startsWith("Create") && !commit.commit.message.includes("footer"))
                })
            ).then((filtered) => {
              console.log(filtered)
            });
